<?php
	return array(
		'礼堂' => 'SpriteOutput/RandomHappeningPic/Command_Theatre',
		'商业街' => 'SpriteOutput/RandomHappeningPic/Puri_Shop',
		'浴池' => 'SpriteOutput/RandomHappeningPic/Stove_Spring',
		'咖啡馆' => 'SpriteOutput/RandomHappeningPic/Port_Cafe',
		'射击训练室默认' => 'SpriteOutput/RandomHappeningPic/KianaBoost_Default',
		'剑道训练室默认' => 'SpriteOutput/RandomHappeningPic/MeiBoost_Default',
		'机甲训练室默认' => 'SpriteOutput/RandomHappeningPic/BronyaBoost_Default',
		'姬子训练室默认' => 'SpriteOutput/RandomHappeningPic/HimekoBoost_Default',
		'德丽莎训练室默认' => 'SpriteOutput/RandomHappeningPic/Theresa_Default',
		'家园主界面' => 'SpriteOutput/RandomHappeningPic/MainBG',
		'神社' => 'SpriteOutput/RandomHappeningPic/Stove_Shrine',
		'海滩' => 'SpriteOutput/RandomHappeningPic/Port_Beach',
		'游乐园' => 'SpriteOutput/RandomHappeningPic/Puri_Playground',
		'教室' => 'SpriteOutput/RandomHappeningPic/Command_Classroom',
		'吼姆欢乐餐厅' => 'SpriteOutput/RandomHappeningPic/HomuRestrant',
		'海滨度假村' => 'SpriteOutput/RandomHappeningPic/SeasideFestival',
		'米哈游大楼' => 'SpriteOutput/RandomHappeningPic/MihoyoBuilding',
		'吼姆吼姆游乐园' => 'SpriteOutput/RandomHappeningPic/Puri_Playground',
		'游戏机中心' => 'SpriteOutput/RandomHappeningPic/GameCenter',
		'商店街' => 'SpriteOutput/RandomHappeningPic/Puri_Shop',
		'八重诊所' => 'SpriteOutput/RandomHappeningPic/SakuraClinic',
		'圣芙蕾雅学园' => 'SpriteOutput/RandomHappeningPic/SchoolRoom',
		'吼姆纪念堂' => 'SpriteOutput/RandomHappeningPic/Stove_Shrine',
		'逆熵秘密基地' => 'SpriteOutput/RandomHappeningPic/SecretBase',
		'姬子房间' => 'SpriteOutput/RandomHappeningPic/GirlsRoom',
		'姬子房间夜' => 'SpriteOutput/RandomHappeningPic/GirlsRoom_Night',
		'吼姆快乐餐厅夜' => 'SpriteOutput/RandomHappeningPic/HomuRestrant_Night',
		'大厦天台夜' => 'SpriteOutput/RandomHappeningPic/MihoyoBuilding_Night',
		'夜间小巷' => 'SpriteOutput/RandomHappeningPic/SecretBase_Night',
		'黑幕' => 'SpriteOutput/RandomHappeningPic/BlackBg',
		'虚数蓝'=>'SpriteOutput/RandomHappeningPic/ImaginarySpace',
		'虚数紫'=>'SpriteOutput/RandomHappeningPic/ImaginarySpace_Purple',
		'学院外'=>'SpriteOutput/RandomHappeningPic/SchoolOutside',
		'月光王座舰桥'=>'SpriteOutput/RandomHappeningPic/SpaceShipInside',
		'无'=>''
	);
?>